config/routes.rb
Rails.application.routes.draw do
  resources :contact, only: [:create]

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def create
    @contact_form = ContactForm.new(contact_form_params)

    @contact_form.call
  end

  private

  def contact_form_params
    params.require(:contact_form).permit(:name, :email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @contact_form = ContactForm.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/_contact_form.html.erb
<%= tag.div id: dom_id(contact_form), class: "form__container", data: { stream_exit_class: "success" } do %>
  <%= form_with model: contact_form, url: contact_index_path, html: { novalidate: true }, data: {
        controller: "form",
        form_target: "form"
      } do |form| %>
    <div class="form__field">
      <%= form.label :name, class: "label form__label" %>
      <%= form.text_field :name, class: "input input--text form__input--text", required: true, data: { error_message: "required" } %>
    </div>
    <div class="form__field">
      <%= form.label :email, class: "label form__label" %>
      <%= form.email_field :email, class: "input input--text form__input--text", required: true, data: { error_message: "We need a valid email here :)" } %>
    </div>
    <div class="form__field">
      <%= form.label :message, class: "label form__label" %>
      <%= form.text_area :message, class: "input input--textarea form__input--textarea", required: true, data: { error_message: "required" } %>
    </div>
    <div class="form__actions">
      <%= form.submit "Send", class: "button button--primary form__button", disabled: true %>
    </div>
  <% end %>
  <div class="thanks">
    <h2>Thanks for reaching out.</h2>
    <p>The robuts are delivering the mail, and we'll be in touch soon!</p>
  </div>
<% end %>

app/views/contact/create.turbo_stream.erb
<%= turbo_stream.replace dom_id(@contact_form), partial: "contact_form", locals: { contact_form: @contact_form } %>

app/views/home/index.html.erb
<div class="container">
  <p>Hey there! Welcome to grouch.dev, where we're all about turning grumbles into greatness. We embrace the grumpiness that can sometimes accompany the ever-changing world of technology. Our name is a nod to those grouchy moments we've all experienced when faced with a new challenge or change. But, you know what? A sprinkle of understanding, a dash of knowledge, and a heap of empathy can turn any frown upside down.</p>

  <p>Based out of the vibrant Asheville, NC area, we are proud to be part of a community that values creativity, collaboration, and innovation. In today's digital world, we're all neighbors, and we're committed to making our global neighborhood a better place!</p>
</div>
<div class="container">
  <div class="tiles">
    <div class="tile tile--yellow">
      <h3> Contract Programming</h3>
      <p>Need an experienced programmer to bring your project to life? Look no further! With experience in Ruby on Rails, and React, we offer contract programming services to meet your unique needs and help you achieve your business goals.</p>
      <p class="icon">👨‍💻</p>
    </div>

    <div class="tile tile--red">
      <h3>Small Business Email & Website Support</h3>
      <p>Navigating the digital world can be tricky, but we're here to help! We provide small business email support and website assistance to ensure your communication tools and online presence are top-notch.</p>
      <p class="icon">📧</p>
    </div>

    <div class="tile tile--blue">
      <h3>Custom Websites</h3>
      <p>In addition to our programming and support services, we also create small custom websites tailored to your specific requirements. Whether you need a professional online portfolio, a sleek landing page, or an easy-to-navigate blog, we've got you covered.</p>
      <p class="icon">💻</p>
    </div>
  </div>
</div>
<div class="container">
  <h2>Say Hello</h2>
  <p>Ready to turn your ideas into reality? We'd love to hear from you! Fill out the form, and let's get started!</p>
  <%= render partial: "contact/contact_form", locals: { contact_form: @contact_form } %>
</div>
<div class="container">
  <h2>A Little More About Us</h2>
  <p>We believe in giving back. Our business is not just about profits. It's about making a positive impact, both locally and globally! We are dedicated to supporting initiatives and organizations that strive to improve the lives of those in our community and around the world.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grouch Dev</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.typekit.net/zvg3tgv.css">
    <link rel="icon" href="/favicon.ico" sizes="32x32">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="manifest" href="/manifest.webmanifest">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render partial: "shared/header" %>
    <main>
      <%= yield %>
    </main>
    <%= render partial: "shared/footer" %>
  </body>
</html>

app/views/shared/_contact_form.html.erb
<div class="form__container">
  <%= form_with model: @contact_form, url: contact_index_path, local: true do |form| %>
    <% if @contact_form.errors.any? %>
      <div class="form__errors" id="error_explanation">
        <h2><%= pluralize(@contact_form.errors.count, "error") %> prohibited this contact form from being saved:</h2>
        <ul>
          <% @contact_form.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form__field">
      <%= form.label :name, class: "label form__label" %>
      <%= form.text_field :name, class: "input input--text form__input--text" %>
    </div>
    <div class="form__field">
      <%= form.label :email, class: "label form__label" %>
      <%= form.text_field :email, class: "input input--text form__input--text" %>
    </div>
    <div class="form__field">
      <%= form.label :message, class: "label form__label" %>
      <%= form.text_area :message, class: "input input--textarea form__input--textarea" %>
    </div>
    <div class="form__actions">
      <%= form.submit "Submit", class: "button button--primary form__button" %>
    </div>
  <% end %>
</div>

app/views/shared/_footer.html.erb
<footer class="footer footer--primary container">
  <p>Under construction & made with ♡ by grouch.dev</p>
</footer>

app/views/shared/_header.html.erb
<header class="header header--primary">
  <%= render partial: "shared/logo" %>
  <div class="blocks">
    <div class="block bg--yellow"></div>
    <div class="block bg--red"></div>
    <div class="block bg--blue"></div>
    <div class="block bg--purple"></div>
    <div class="block bg--green"></div>
  </div>
</header>
<header class="header header--super"></header>

app/views/shared/_logo.html.erb
<div class="logo__wrapper">
  <h1 class="logo">grouch</h1>
</div>